# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zack's Workbench
email: website@zlittell.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my workbench.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zlittell
github_username: zlittell
repository: "zlittell/zlittell.github.io"
minimal_mistakes_skin: dark
search: true
title_separator: "|"
permalink: /:categories/:title/
timezone: America/Chicago

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages
author:
  name   : "Zack Littell"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Electronics design engineer looking to not always work on work stuff for work."
  links:
    - label: "Zack's Workbench"
      icon: "fas fa-fw fa-link"
      url: "https://www.zlittell.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zlittell/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zlittell"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zlittell"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/zlittell/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zlittell"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zlittell"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

